config/routes.rb
Rails.application.routes.draw do
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  mount Arclight::Engine => '/'

  root to: 'arclight/repositories#index'
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable
  end

  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: "users/omniauth_callbacks" },
             skip: [:sessions, :passwords, :registration]
  # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'users/auth/cas', to: 'users/omniauth_authorize#passthru', defaults: { provider: :cas }, as: "new_user_session"
    get('global_sign_out',
        to: 'users/sessions#global_logout',
        as: :destroy_global_session)
    get "users/auth/cas",
        to: 'users/omniauth_authorize#passthru',
        defaults: { provider: :cas }, as: "new_cas_user_session"
  end

  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  get '/admin', to: 'admin#index', as: 'admin'
  get 'admin/index_eads', to: 'admin#index_eads', as: 'index_eads'
  get 'admin/index_repository', to: 'admin#index_repository', as: 'index_repository'
  get 'admin/index_ead', to: 'admin#index_ead', as: 'index_ead'
  delete 'admin/delete_user/:id', to: 'admin#delete_user', as: 'admin_delete_user'
  get 'admin/update_user_role/:id', to: 'admin#update_user_role', as: 'admin_update_user_role'
  get 'admin/edit_repository/:id', to: 'admin#edit_repository', as: 'admin_edit_repository'
  patch 'admin/update_repository/:id', to: 'admin#update_repository', as: 'admin_update_repository'

  authenticated :user do
    mount DelayedJobWeb, at: '/delayed_job'
  end

  get '/about', to: 'pages#about', as: 'about'
  get '/contribute', to: 'pages#contribute', as: 'contribute'
  get '/help', to: 'pages#help', as: 'help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Connects this user object to Blacklights Bookmarks.
  include Blacklight::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :invitable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:cas]

  has_and_belongs_to_many :repositories

  enum role: { manager: 0, admin: 1 }
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :manager
  end

  scope :admins, -> { where(role: :admin) }

  # Method added by Blacklight; Blacklight uses #to_s on your
  # user class to get a user-displayable login/identifier for
  # the account.
  def to_s
    email
  end

  def self.find_for_iu_cas(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = [auth.uid,'@iu.edu'].join
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/views/admin/edit_repository.html.erb
<h2>Edit Repositories for <%= @user.email %></h2>
<%= form_for @user, url: admin_update_repository_path(@user) do |f| %>
  <%= hidden_field_tag(:user_id, @user.id) %>
  <div class="form-group">
  
    <%= f.select :repository_ids, options_from_collection_for_select(Repository.all, :id, :name), {}, 
      { multiple: true, class: "form-control" } %>
    </div>
  <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/admin/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ul class="nav nav-tabs nav-fill" id="adminTab" role="tablist">
        <li class="nav-item flex-fill">
          <a class="nav-link active" id="manage-repositories-tab" data-toggle="tab" href="#manage-repositories" role="tab" aria-controls="manage-repositories" aria-selected="true">Manage Repositories</a>
        </li>
        <% if current_user.admin? %>
        <li class="nav-item flex-fill">
          <a class="nav-link" id="manage-users-tab" data-toggle="tab" href="#manage-users" role="tab" aria-controls="manage-users" aria-selected="false">Manage Users</a>
        </li>
        <% end %>
      </ul>
      <div class="tab-content" id="adminTabContent">
        <div class="tab-pane fade show active" id="manage-repositories" role="tabpanel" aria-labelledby="manage-repositories-tab">
          <h3>Manage Repositories</h3>
          <% if current_user.admin? %>
            <div class="row col">
              <%= link_to "Index all EADs for all repositories", index_eads_url, class: "btn btn-lg btn-primary mt-4 mb-4" %>
            </div>
          <% end %>
        
          <div class="row mb-1">
          </div>
          <% @repositories.each do |repo| %>
            <div class="row mt-2 pt-4 border-top">
              <div class="col-md-9">
                <h5><%= repo.name %></h5>
              </div>
              <div class="col-md-3">
                <%= link_to "Index all EADs in this repository", index_repository_url(repository: repo.repository_id), class: 'btn btn-primary' %>
              </div>
            </div>
            <div class="row pb-4">
              <div class="col-md-12">
                <table class="table">
                  <thead>
                    <tr>
                      <th>Eads in this Repository</th>
                      <th>Last Update</th>
                      <th>Last Index</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% repo.eads.each do |ead| %>
                      <% last_update = ead.last_updated_at.present? ? ead.last_updated_at : ead.repository&.last_updated_at %>
                      <% needs_update_style = !ead.last_indexed_at.present? || (ead.last_indexed_at.present? && last_update > ead.last_indexed_at) ? 'needs-update' : 'no-update' %>
                      <tr class="<%= needs_update_style %>">
                        <td><%= ead.filename %></td>
                        <td><%= last_update&.strftime("%m/%d/%Y at %I:%M%p") %></td>
                        <td><%= ead.last_indexed_at&.strftime("%m/%d/%Y at %I:%M%p") %></td>
                        <td>
                          <%= link_to "Index", index_ead_url(repository: repo.repository_id, ead: ead.filename), class: 'btn btn-sm btn-primary' %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          <% end %>
        </div>
        <% if current_user.admin? %>
        <div class="tab-pane fade" id="manage-users" role="tabpanel" aria-labelledby="manage-users-tab">
          <h3>Manage Users</h3>
          <% if current_user.admin?%>
            <div class="row col">
              <%= link_to "Invite a new user", new_user_invitation_path, class: "btn btn-lg btn-primary mt-4 mb-4"%>
            </div>
          <% end %>
          <div class="row">
            <div class="col-md-12">
              <table class="table">
                <thead>
                  <tr>
                    <th>User</th>
                    <th>Role</th>
                    <th>Repositories</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <% @users.each do |user| %>
                    <tr>
                      <td><%= user.email%></td>
                      <td><%= user.role %></td>
                      <td>
                        <% if user.admin? %>
                          All repositories
                        <% else %>
                          <% user.repositories.each do |r| %>
                            <%= r.name %><br/>
                          <% end %>
                        <% end %>
                      </td>
                      <td>
                        <%= link_to "Delete", admin_delete_user_path(user), class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: "Are you sure you want to delete this user?" } %>
                        <% if user.role == "admin"%>
                          <%= link_to "Make Manager", admin_update_user_role_path(user), class: 'btn btn-primary btn-sm' %>
                        <% else %>
                          <%= link_to "Make Admin", admin_update_user_role_path(user), class: 'btn btn-primary btn-sm' %>
                        <% end %>
                        <% unless user.admin? %>
                          <%= link_to 'Edit Repositories', admin_edit_repository_path(user), class: 'btn btn-primary btn-sm' %>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>