config/routes.rb
Rails.application.routes.draw do
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  mount Arclight::Engine => '/'

  root to: 'arclight/repositories#index'
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable
  end

  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: "users/omniauth_callbacks" },
             skip: [:sessions, :passwords, :registration]
  # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'users/auth/cas', to: 'users/omniauth_authorize#passthru', defaults: { provider: :cas }, as: "new_user_session"
    get('global_sign_out',
        to: 'users/sessions#global_logout',
        as: :destroy_global_session)
    get "users/auth/cas",
        to: 'users/omniauth_authorize#passthru',
        defaults: { provider: :cas }, as: "new_cas_user_session"
  end

  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  get '/admin', to: 'admin#index', as: 'admin'
  get 'admin/index_eads', to: 'admin#index_eads', as: 'index_eads'
  get 'admin/index_repository', to: 'admin#index_repository', as: 'index_repository'
  get 'admin/index_ead', to: 'admin#index_ead', as: 'index_ead'
  delete 'admin/delete_user/:id', to: 'admin#delete_user', as: 'admin_delete_user'
  get 'admin/update_user_role/:id', to: 'admin#update_user_role', as: 'admin_update_user_role'
  get 'admin/edit_repository/:id', to: 'admin#edit_repository', as: 'admin_edit_repository'
  patch 'admin/update_repository/:id', to: 'admin#update_repository', as: 'admin_update_repository'

  authenticated :user do
    mount DelayedJobWeb, at: '/delayed_job'
  end

  get '/about', to: 'pages#about', as: 'about'
  get '/contribute', to: 'pages#contribute', as: 'contribute'
  get '/help', to: 'pages#help', as: 'help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<%= render 'shared/ngao_footer'%>
<%= render 'shared/iu_footer'%>

app/views/shared/_header_navbar.html.erb
<!--overriding from arclight 0.3.1 to remove devise and add IU header branding_bar, from https://assets.iu.edu/brand/3.2.x/header-iu.html -->
<header>
  <%= render '/layouts/branding_bar' %>
  <%# ADD IU BRANDING AND REMOVE BLACK NAVBAR %>

  <% if controller_name == 'catalog' && !has_search_parameters? && action_name == 'index' %>
    <div class='al-homepage-masthead jumbotron'>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-8 masthead-center" >
            <%= link_to t('arclight.masthead_heading'), root_path, class: 'h1' %>
          </div>

          <div class="col-md-4 nav-links d-flex justify-content-end" >
            <ul class="navbar-nav" aria-label="browse" role="navigation">
              <%= render 'shared/main_menu_links' %>
            </ul>
          </div>
        </div>

        <div class='row justify-content-md-center'>
          <div class='col-12'>
            <div class='navbar-search'>
              <%= render_search_bar %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class='bg-faded al-masthead'>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-8" >
            <%= link_to t('arclight.masthead_heading'), root_path, class: 'h1' %>
          </div>

          <div class="col-md-4 nav-links d-flex justify-content-end" >
            <ul class="navbar-nav" aria-label="browse" role="navigation">
              <%= render 'shared/main_menu_links' %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar-search navbar">
      <div class="<%= container_classes %>">
        <%= render_search_bar  %>
      </div>
    </div>
  <% end %>
</header>

app/views/shared/_iu_footer.html.erb
<!--imported from https://assets.iu.edu/brand/3.2.x/footer.html with modifications for image-->
<footer id="footer" role="contentinfo" itemscope="itemscope" itemtype="http://schema.org/CollegeOrUniversity">
  <div class="row pad">
    <div class="footer-links">
      <p class="signature">
        <a href="https://www.iu.edu/" class="signature-link signature-img">
          <%= image_tag('iu-sig-formal.svg') %>
        </a>
      </p>
      <p class="copyright">
        <span class="line-break"><a href="https://accessibility.iu.edu/assistance" id="accessibility-link" title="Having trouble accessing this web page content? Please visit this page for assistance.">Accessibility</a> | <a href="https://libraries.indiana.edu/privacy" id="privacy-policy-link">Privacy Notice</a></span>
        <span class="hide-on-mobile"> | </span>
        <a href="https://www.iu.edu/copyright/index.html">Copyright</a> © 2020 <span class="line-break-small">The Trustees of <a href="https://www.iu.edu/" itemprop="url"><span itemprop="name">Indiana University</span></a></span>
      </p>
    </div>
  </div>
</footer>

app/views/shared/_main_menu_links.html.erb
<%# IMPORTED FROM ARCLIGHT to add user auth links %>
<li class="nav-item <%= repositories_active_class %>">
  <%= link_to t('arclight.routes.repositories'), arclight_engine.repositories_path, class: 'nav-link' %>
</li>
<li class="nav-item ml-3 <%= collection_active_class %>">
  <%= link_to t('arclight.routes.collections'), arclight_engine.collections_path, class: 'nav-link' %>
</li>

app/views/shared/_ngao_footer.html.erb
<footer id="ngao-footer">
  <div class="row pad ngao-links">
    <div class="link-caddy">
      <%= render 'shared/static_pages_links' %>
      <%= render 'shared/user_auth_links' %>
    </div>
  </div>
</footer>

app/views/shared/_show_breadcrumbs.html.erb
<%# COPIED FROM ARCLIGHT TO ADD CAMPUS TO BREADCRUMBS %>
<% parents = Arclight::Parents.from_solr_document(document).as_parents %>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-home-link">
      <%= link_to t('arclight.routes.home'), root_path %>
    </li>
    <li class="media breadcrumb-item breadcrumb-item-1">
      <% if document.campus.present? %>
        <span class="media-body" aria-hidden="true"><%= blacklight_icon :campus, classes: 'al-campus-content-icon' %></span>
        <span class="col"><%= add_campus_link(document) %></span>
      <% elsif document.parent_campus.present? %>
        <span class="media-body" aria-hidden="true"><%= blacklight_icon :campus, classes: 'al-campus-content-icon' %></span>
        <span class="col"><%= add_parent_campus_link(document) %></span>
      <% else %>
        <span class="media-body" aria-hidden="true"><%= blacklight_icon :campus, classes: 'al-campus-content-icon' %></span>
        <span class="col">Indiana University</span>
      <% end %>
    </li>
    <li class="media breadcrumb-item breadcrumb-item-2">
      <% if document.repository_config.present? %>
        <span class="media-body" aria-hidden="true"><%= blacklight_icon :repository, classes: 'al-repository-content-icon' %></span>
        <span class="col"><%= link_to(document.repository_config.name, arclight_engine.repository_path(document.repository_config.slug)) %></span>
      <% else %>
          <span class="media-body" aria-hidden="true"><%= blacklight_icon :repository, classes: 'al-repository-content-icon' %></span><span class="col"><%= t('arclight.show_breadcrumb_label') %></span>
      <% end %>
    </li>
    <% parents.each_with_index.map do |parent, index| %>
      <%= content_tag :li, class: "breadcrumb-item breadcrumb-item-#{index + 3} media" do %>
        <span class="media-body" aria-hidden="true"><%= blacklight_icon "arrow-return-right" %></span>
        <span class="col"><%= link_to parent.label, solr_document_path(parent.global_id) %></span>
      <% end %>
    <% end %>
  </ol>

  <%= content_tag :h1, class: "breadcrumb-item breadcrumb-item-#{parents.length + 4} media" do %>
    <span class="media-body" aria-hidden="true"><%= blacklight_icon "arrow-return-right" %></span>
    <span class="col"><%= document.normalized_title %></span>
  <% end %>
</nav>

app/views/shared/_static_pages_links.html.erb
<li class="nav-item ml-3"> <%= link_to 'About', about_path, class: 'nav-link' %></li>
<li class="nav-item ml-3"> <%= link_to 'Contribute to AO', contribute_path, class: 'nav-link' %></li>
<%# template for adding new links, just copy and remove the <%#
<%# <li class="nav-item ml-3"> <% link_to 'Label', path_to_link, class: 'nav-link' %></li>

app/views/shared/_user_auth_links.html.erb
<% if current_user %>
  <li class="nav-item ml-3">
    <%= link_to "Admin", admin_path, class: 'nav-link' %>
  </li>
  <li class="nav-item ml-3">
    <%= link_to "Logout", destroy_global_session_path, class: 'nav-link' %>
  </li>
  <li class="nav-item ml-3"><a class="nav-link" href="http://www.dlib.indiana.edu/collections/findingaids">Legacy Archives Online</a></li>
<% else %>
  <li class="nav-item ml-3">
    <%= link_to "Admin", admin_path, class: 'nav-link' %>
  </li>
  <li class="nav-item ml-3"><a class="nav-link" href="http://www.dlib.indiana.edu/collections/findingaids">Legacy Archives Online</a></li>
<% end %>