config/routes.rb
Rails.application.routes.draw do
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  mount Arclight::Engine => '/'

  root to: 'arclight/repositories#index'
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable
  end

  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: "users/omniauth_callbacks" },
             skip: [:sessions, :passwords, :registration]
  # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'users/auth/cas', to: 'users/omniauth_authorize#passthru', defaults: { provider: :cas }, as: "new_user_session"
    get('global_sign_out',
        to: 'users/sessions#global_logout',
        as: :destroy_global_session)
    get "users/auth/cas",
        to: 'users/omniauth_authorize#passthru',
        defaults: { provider: :cas }, as: "new_cas_user_session"
  end

  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  get '/admin', to: 'admin#index', as: 'admin'
  get 'admin/index_eads', to: 'admin#index_eads', as: 'index_eads'
  get 'admin/index_repository', to: 'admin#index_repository', as: 'index_repository'
  get 'admin/index_ead', to: 'admin#index_ead', as: 'index_ead'
  delete 'admin/delete_user/:id', to: 'admin#delete_user', as: 'admin_delete_user'
  get 'admin/update_user_role/:id', to: 'admin#update_user_role', as: 'admin_update_user_role'
  get 'admin/edit_repository/:id', to: 'admin#edit_repository', as: 'admin_edit_repository'
  patch 'admin/update_repository/:id', to: 'admin#update_repository', as: 'admin_update_repository'

  authenticated :user do
    mount DelayedJobWeb, at: '/delayed_job'
  end

  get '/about', to: 'pages#about', as: 'about'
  get '/contribute', to: 'pages#contribute', as: 'contribute'
  get '/help', to: 'pages#help', as: 'help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/catalog_controller.rb
# frozen_string_literal: true

class CatalogController < ApplicationController
  include Blacklight::Catalog
  include BlacklightRangeLimit::ControllerOverride

  include Arclight::Catalog
  include Arclight::FieldConfigHelpers

  configure_blacklight do |config|
    ## Class for sending and receiving requests from a search index
    # config.repository_class = Blacklight::Solr::Repository
    #
    ## Class for converting Blacklight's url parameters to into request parameters for the search index
    # config.search_builder_class = ::SearchBuilder
    #
    ## Model that maps search index responses to the blacklight response model
    # config.response_model = Blacklight::Solr::Response

    ## Default parameters to send to solr for all search-like requests. See also SearchBuilder#processed_parameters
    config.default_solr_params = {
      rows: 10
    }

    # solr path which will be added to solr base url before the other solr params.
    # config.solr_path = 'select'

    # items to show per page, each number in the array represent another option to choose from.
    # config.per_page = [10,20,50,100]

    ## Default parameters to send on single-document requests to Solr. These settings are the Blacklight defaults (see SearchHelper#solr_doc_params) or
    ## parameters included in the Blacklight-jetty document requestHandler.
    #
    # config.default_document_solr_params = {
    #  qt: 'document',
    #  ## These are hard-coded in the blacklight 'document' requestHandler
    #  # fl: '*',
    #  # rows: 1,
    #  # q: '{!term f=id v=$id}'
    # }

    # solr field configuration for search results/index views
    config.index.title_field = 'normalized_title_ssm'
    config.index.display_type_field = 'level_ssm'
    # config.index.thumbnail_field = 'thumbnail_path_ss'

    # solr field configuration for document/show views
    # config.show.title_field = 'title_display'
    config.show.display_type_field = 'level_ssm'
    # config.show.thumbnail_field = 'thumbnail_path_ss'

    ##### REMOVE BOOKMARKS #####
    # config.add_results_document_tool(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)

    config.add_results_collection_tool(:sort_widget)
    config.add_results_collection_tool(:per_page_widget)
    config.add_results_collection_tool(:view_type_group)

    ##### REMOVE BOOKMARK #####
    # config.add_show_tools_partial(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)
    config.add_show_tools_partial(:email, callback: :email_action, validator: :validate_email_params)
    config.add_show_tools_partial(:sms, if: :render_sms_action?, callback: :sms_action, validator: :validate_sms_params)
    config.add_show_tools_partial(:citation)

    ##### REMOVE BOOKMARK AND HISTORY FROM NAVBAR #####
    # config.add_nav_action(:bookmark, partial: 'blacklight/nav/bookmark', if: :render_bookmarks_control?)
    # config.add_nav_action(:search_history, partial: 'blacklight/nav/search_history')

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    #
    # set :index_range to true if you want the facet pagination view to have facet prefix-based navigation
    #  (useful when user clicks "more" on a large facet and wants to navigate alphabetically across a large set of results)
    # :index_range can be an array or range of prefixes that will be used to create the navigation (note: It is case sensitive when searching values)

    config.add_facet_field 'collection_sim', label: 'Collection', limit: 10
    config.add_facet_field 'creator_ssim', label: 'Creator', limit: 10
    config.add_facet_field 'creators_ssim', label: 'Creator', show: false
    config.add_facet_field 'date_range_sim', label: 'Date range', range: true
    config.add_facet_field 'level_sim', label: 'Level', limit: 10
    config.add_facet_field 'names_ssim', label: 'Names', limit: 10
    config.add_facet_field 'repository_sim', label: 'Repository', limit: 10
    config.add_facet_field 'geogname_sim', label: 'Place', limit: 10
    config.add_facet_field 'places_ssim', label: 'Places', show: false
    config.add_facet_field 'access_subjects_ssim', label: 'Subject', limit: 10
    config.add_facet_field 'component_level_isim', show: false
    config.add_facet_field 'parent_ssim', show: false
    config.add_facet_field 'campus_unit_sim', label: 'Campus', helper_method: :render_campus_facet
    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    config.add_index_field 'unitid_ssm', label: 'Unit ID'
    config.add_index_field 'repository_ssm', label: 'Repository'
    config.add_index_field 'campus_unit_ssm', label: 'Campus', helper_method: :render_campus_name
    config.add_index_field 'normalized_date_ssm', label: 'Date'
    config.add_index_field 'creator_ssm', label: 'Creator'
    config.add_index_field 'language_ssm', label: 'Language'
    config.add_index_field 'scopecontent_ssm', label: 'Scope Content', helper_method: :render_html_tags
    config.add_index_field 'extent_ssm', label: 'Physical Description'
    config.add_index_field 'accessrestrict_ssm', label: 'Conditions Governing Access', helper_method: :render_html_tags
    config.add_index_field 'collection_ssm', label: 'Collection Title'
    config.add_index_field 'geogname_ssm', label: 'Place'

    config.add_facet_field 'has_online_content_ssim', label: 'Access', query: {
      online: { label: 'Online access', fq: 'has_online_content_ssim:true' }
    }

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display

    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject
    # that specifies the same :qt as default for our own internal
    # testing purposes.
    #
    # The :key is what will be used to identify this BL search field internally,
    # as well as in URLs -- so changing it after deployment may break bookmarked
    # urls.  A display label will be automatically calculated from the :key,
    # or can be specified manually to be different.

    # This one uses all the defaults set by the solr request handler. Which
    # solr request handler? The one set in config[:default_solr_parameters][:qt],
    # since we aren't specifying it otherwise.
    config.add_search_field 'all_fields', label: 'All Fields' do |field|
      field.include_in_simple_select = true
    end

    config.add_search_field 'within_collection' do |field|
      field.include_in_simple_select = false
      field.solr_parameters = {
        fq: '-level_sim:Collection'
      }
    end

    # Field-based searches. We have registered handlers in the Solr configuration
    # so we have Blacklight use the `qt` parameter to invoke them
    config.add_search_field 'keyword', label: 'Keyword' do |field|
      field.qt = 'search' # default
    end
    config.add_search_field 'name', label: 'Name' do |field|
      field.qt = 'search'
      field.solr_parameters = {
        qf:  '${qf_name}',
        pf:  '${pf_name}'
      }
    end
    config.add_search_field 'place', label: 'Place' do |field|
      field.qt = 'search'
      field.solr_parameters = {
        qf:  '${qf_place}',
        pf:  '${pf_place}'
      }
    end
    config.add_search_field 'subject', label: 'Subject' do |field|
      field.qt = 'search'
      field.solr_parameters = {
        qf:  '${qf_subject}',
        pf:  '${pf_subject}'
      }
    end
    config.add_search_field 'title', label: 'Title' do |field|
      field.qt = 'search'
      field.solr_parameters = {
        qf:  '${qf_title}',
        pf:  '${pf_title}'
      }
    end
    config.add_search_field 'unitid', label: 'Unit ID' do |field|
      field.qt = 'search'
      field.solr_parameters = {
        qf:  '${qf_unitid}',
        pf:  '${pf_unitid}'
      }
    end

    # "sort results by" select (pulldown)
    # label in pulldown is followed by the name of the SOLR field to sort by and
    # whether the sort is ascending or descending (it must be asc or desc
    # except in the relevancy case).
    config.add_sort_field 'score desc, title_sort asc', label: 'relevance'
    config.add_sort_field 'date_sort asc', label: 'date (ascending)'

app/views/catalog/_arclight_index_compact_default.html.erb
<%# COPIED FROM ARCLIGHT TO ADD NUMBERING TO SEARCH RESULTS %>
<div class="documentHeader row">
  <% counter = document_counter_with_offset(document_counter) %>
  <div class="col-auto">
    <%= blacklight_icon document_or_parent_icon(document) %>
  </div>
  <div class="col col-no-left-padding col-no-right-padding">
    <div class="d-flex justify-content-between">
      <h3 class="col col-no-left-padding">
        <%# ADDED NUMBERING TO SEARCH RESULTS %>
        <% if counter = document_counter_with_offset(document_counter) %>
          <span class="document-counter">
            <%= t('blacklight.search.documents.counter', counter: counter) %>
          </span>
        <% end %>
        <%= link_to_document document, document_show_link_field(document), counter: document_counter %>
      </h3>
      <%= render_index_doc_actions document %>
    </div>
    <div class="row">
      <%= content_tag('div', class: 'al-document-highlight col') do %>
        <%= document.highlights.join('<br/>').html_safe %>
      <% end if document.highlights %>
    </div>
    <div class='breadcrumb-links media'>
      <span class="media-body" aria-hidden="true"><%= blacklight_icon :repository, classes: 'al-repository-content-icon' %></span>
    <span class="col ml-2 pl-0" ><%= regular_compact_breadcrumbs(document) %></span>
    </div>
  </div>
</div>

app/views/catalog/_arclight_index_default.html.erb
<%# COPIED FROM ARCLIGHT TO ADD NUMBERING TO SEARCH RESULTS %>
<div class="al-search-result-index-article row d-flex align-items-start">
  <% counter = document_counter_with_offset(document_counter) %>
  <div class="col-auto">
    <%= render partial: 'arclight_document_header_icon', locals: { document: document }  %>
  </div>

  <div class="col col-no-left-padding d-flex flex-wrap">
    <div class="documentHeader my-w-75 w-md-100 order-0" data-document-id="<%= document.id %>">
      <h3 class="index_title document-title-heading">
        <%# ADDED NUMBERING TO SEARCH RESULTS %>
        <% if counter = document_counter_with_offset(document_counter) %>
          <span class="document-counter">
            <%= t('blacklight.search.documents.counter', counter: counter) %>
          </span>
        <% end %>
        <%= link_to_document document, document_show_link_field(document), counter: counter %>
        <%= content_tag('span', class: 'al-document-extent badge') do %>
          <%= document.extent %>
        <% end if document.extent %>
      </h3>
    </div>

    <div class="my-w-25 w-md-100 order-12 order-md-1">
      <%= render_index_doc_actions document, wrapping_class: 'd-flex justify-content-end' %>
    </div>

    <div class="order-2">
      <div class="row">
        <%= content_tag('div', class: 'al-document-highlight col') do %>
          <%= document.highlights.join('<br/>').html_safe %>
        <% end if document.highlights %>
      </div>

      <div class="row">
        <%= content_tag('div', class: 'al-document-creator col') do %>
          <%= document.creator %>
        <% end if document.creator %>
      </div>

      <div class="row">
        <%= content_tag('div', class: 'al-document-abstract-or-scope col') do %>
          <%= content_tag('div', 'data-arclight-truncate' => true) do %>
            <%= document.abstract_or_scope %>
          <% end %>
        <% end if document.abstract_or_scope %>
      </div>

      <%= render partial: 'index_breadcrumb_default', locals: { document: document } %>
    </div>
  </div>
</div>

app/views/catalog/_arclight_index_group_document_compact_default.html.erb
<%# COPIED FROM ARCLIGHT TO ADD NUMBERING TO SEARCH RESULTS %>
<article class="document">
  <% counter = document_counter(document_counter) %>
  <% breadcrumbs = component_top_level_parent_to_links(document) %>
  <div class="documentHeader row">
    <div class="col-auto">
      <%= blacklight_icon document_or_parent_icon(document) %>
    </div>
    <div class="col col-no-left-padding">
      <h4>
        <%# ADDED NUMBERING TO SEARCH RESULTS %>
        <% if counter = document_counter(document_counter) %>
          <span class="document-counter">
            <%= t('blacklight.search.documents.counter', counter: counter) %>
          </span>
        <% end %>
        <%= link_to_document document, document_show_link_field(document), counter: document_counter %>
      </h4>
      <div class='breadcrumb-links media'>
        <% unless breadcrumbs.nil? %>
          <span class="media-body" aria-hidden="true"><%= blacklight_icon :folder, classes: 'al-folder-icon' %></span>
          <span class="col" ><%= component_top_level_parent_to_links(document) %></span>
        <% end %>
      </div>
    </div>
  </div>
</article>

app/views/catalog/_arclight_index_group_document_default.html.erb
<%# COPIED FROM ARCLIGHT TO ADD NUMBERING TO SEARCH RESULTS %>
<article class="document">
  <% counter = document_counter(document_counter) %>
  <% breadcrumbs = parents_to_links(document) %>
  <div class="documentHeader row">
    <div class="col-auto">
      <%= blacklight_icon document_or_parent_icon(document) %>
    </div>
    <div class="col col-no-left-padding">
      <h4>
        <%# ADDED NUMBERING TO SEARCH RESULTS %>
        <% if counter = document_counter(document_counter) %>
          <span class="document-counter">
            <%= t('blacklight.search.documents.counter', counter: counter) %>
          </span>
        <% end %>
        <%= link_to_document document, document_show_link_field(document), counter: document_counter %>
      </h4>
      <div class='breadcrumb-links media'>
        <% unless breadcrumbs.nil? %>
          <span class="media-body" aria-hidden="true"><%= blacklight_icon :folder, classes: 'al-folder-icon' %></span>
          <span class="col" ><%= parents_to_links(document) %></span>
        <% end %>
    </div>
  </div>
</article>

app/views/catalog/_home_html.erb
<%# COPIED FROM ARCLIGHT SO CUSTOM CONTENT CAN BE LOADED TO HOME PAGE %>
<% @page_title = t('arclight.views.home.title') %>

<%# ADD CUSTOM CONTENT HERE FOR NGAO HOME PAGE CONTENT %>

app/views/catalog/_index_collection_context_default.html.erb
<%# COPIED FROM ARCLIGHT TO REMOVE ICON FROM COLLECTION CONTEXT %>
<li id="<%= document.id %>" class="al-collection-context row d-flex align-items-start">
  <div class="documentHeader row" data-document-id="<%= document.id %>">
    <% requestable = item_requestable?('', { document: document }) %>
    <% if document.children? %>
      <div class="al-toggle-children-container">
        <%= link_to(
          '',
          "##{document.id}-collapsible-hierarchy",
          class: "al-toggle-view-children #{!show_expanded?(document) ? 'collapsed' : ''}",
          'aria-label': t('arclight.hierarchy.view_all'),
            data: {
              toggle: 'collapse'
            }
          )
        %>
      </div>
    <% end %>
    <%# REMOVE ICON FROM COLLECTION CONTEXT %>    
    <div class="col col-no-left-padding d-flex flex-wrap">
      <div class="index_title document-title-heading my-w-75 w-md-100 order-0">
        <% counter = document_counter_with_offset(document_counter) %>
        <%= link_to_document document, document_show_link_field(document), counter: counter %>
        <% if document.children? %>
          <span class="badge badge-pill badge-secondary al-number-of-children-badge"><%= document.number_of_children %><span class="sr-only"><%= t(:'arclight.views.index.number_of_components', count: document.number_of_children) %></span></span>
        <% end %>
      </div>
      
      <div class="my-w-25 w-md-100 order-12 order-md-1">
        <%= render_index_doc_actions document, wrapping_class: 'd-flex justify-content-end' %>
      </div>

      <div class="order-2">
        <div class="row">
          <%= content_tag('div', class: 'al-document-abstract-or-scope mb-0') do %>
            <%= content_tag('div', data: { 'arclight-truncate': true, 'truncate-more': I18n.t('arclight.truncation.view_more'), 'truncate-less': I18n.t('arclight.truncation.view_less') } ) do %>
              <%= document.abstract_or_scope %>
            <% end %>
          <% end if document.abstract_or_scope %>
        </div>
      </div>
    </div>
  </div>
  <% if document.number_of_children > 0 %>
    <%= content_tag(:div, id: "#{document.id}-collapsible-hierarchy",
      class: "collapse al-collection-context-collapsible al-hierarchy-level-#{document.component_level} #{'show' if show_expanded?(document)}",
      data: { resolved: false }
    ) do %>
      <%= generic_context_navigation(document, component_level: document.component_level + 1, original_parents: params[:original_parents]) %>
    <% end %>
  <% end %>
</li>

app/views/catalog/_search_form.html.erb
<% 
# Copied from ArcLight at commit 57dc0ae to specify suggest path for autocomplete
%>

<%
# Overridden from Blacklight to add a drop down that allows the user to choose to search w/i the collection or all collections
%>
<%= form_tag search_action_url, method: :get, class: 'search-query-form pr-0', role: 'search' do %>
  <%= render_hash_as_hidden_fields(search_state.params_for_search.except(:q, :search_field, :qt, :page, :utf8).merge(f: (search_state.params_for_search[:f] || {}).except(:collection_sim))) %>
  <div class="d-md-flex">
    <%= render 'catalog/within_collection_dropdown' %>

    <% if search_fields.length > 1 %>
      <label for="search_field" class="sr-only"><%= t('blacklight.search.form.search_field.label') %></label>
    <% end %>
    <div class="input-group flex-nowrap">
      <% if search_fields.length > 1 %>
          <%= select_tag(:search_field,
                         options_for_select(search_fields, h(params[:search_field])),
                         title: t('blacklight.search.form.search_field.title'),
                         id: "search_field",
                         class: "custom-select search-field") %>
      <% elsif search_fields.length == 1 %>
        <%= hidden_field_tag :search_field, search_fields.first.last %>
      <% end %>

      <label for="q" class="sr-only"><%= t('blacklight.search.form.search.label') %></label>
    
      <%
        # Customizes autocomplete for within collection scope
      %>
      <% if within_collection_context? %>
        <%= text_field_tag :q, 
                          params[:q], 
                          placeholder: t('blacklight.search.form.search.placeholder'), 
                          class: "search-q q rounded-0 form-control", 
                          id: "q", 
                          autofocus: presenter.autofocus?, 
                          data: { autocomplete_enabled: false }  %>
      <% else %>
        <%
          # Use "autocomplete_path: suggest_index_catalog_path" explicitly so that the RepositoriesController gets the appropriate
          # autocomplete path w/o having to have the search form action be local to the controller (by including Blacklight::Catalog)
        %>
        <%= text_field_tag :q, 
                          params[:q], 
                          placeholder: t('blacklight.search.form.search.placeholder'), 
                          class: "search-q q rounded-0 form-control", 
                          id: "q", 
                          autofocus: presenter.autofocus?, 
                          data: { autocomplete_enabled: presenter.autocomplete_enabled?, autocomplete_path: suggest_index_catalog_path }  %>
      <% end %>

      <span class="input-group-append">
        <button type="submit" class="btn btn-primary search-btn" id="search">
          <span class="submit-search-text d-none d-lg-inline"><%= t('blacklight.search.form.submit') %></span>
          <%= blacklight_icon :search, aria_hidden: true %>
        </button>
      </span>
    </div>
  </div>
<% end %>
<%= link_to 'Get search help', help_path, class: 'help-link text-right' %>

app/views/catalog/_show_actions_box_default.html.erb
<%# COPIED FROM ARCLIGHT TO REMOVE BOOKMARK CHECKBOX %>
<div class='al-show-actions-box'>
  <div class="al-actions-box-container">
    <% if document.unitid || document.containers.present? %>
      <div class='al-collection-id'>
        <% if document.unitid %>
          <%= t(:'arclight.views.show.collection_id', id: document.unitid) %>
        <% end %>

        <% if document.unitid && document.containers.present? %>
          <span> | </span>
        <% end %>

        <% if document.containers.present? %>
          <span><%= document.containers.join(', ') %></span>
        <% end %>
      </div>
    <% end %>
    <div class='al-show-actions-box-options d-flex'>
      <%= render partial: 'arclight/requests', locals: { document: document } %>
      <%# REMOVED BOOKMARK PARTIAL %>
    </div>
  </div>

  <%# render document.downloads %>
</div>

app/views/catalog/_show_universal_viewer.html.erb
<div
  class="uv"
  data-locale="en-GB:English (GB),cy-GB:Cymraeg"
  data-config="/uv_config.json"
  data-uri="https://pages.dlib.indiana.edu/concern/scanned_resources/dwh247324p/manifest" 
  data-collectionindex="0"
  data-manifestindex="0"
  data-sequenceindex="0"
  data-canvasindex="0"
  data-xywh="-2204,-248,7873,4957"
  data-rotation="0"
  >
</div>
<script
  type="text/javascript"
  id="embedUV"
  src="https://pages.dlib.indiana.edu/bower_includes/universalviewer/dist/uv-2.0.1/lib/embed.js">
</script>
<script type="text/javascript">/* wordpress fix */</script>

app/views/catalog/_show_upper_metadata_default.html.erb
<% if blacklight_config.show.component_metadata_partials.present? %>
  <% parents = Arclight::Parents.from_solr_document(document).as_parents %>
  <dl class="al-metadata-section">
    <% blacklight_config.show.component_metadata_partials.each do |metadata| %>
      <% doc_presenter = show_presenter(document).with_field_group(metadata) %>
      <% generic_document_fields(metadata).each do |field_name, field| %>
        <% if generic_should_render_field?(metadata, document, field) %>
          <dt class="blacklight-<%= field_name.parameterize %>"><%= generic_render_document_field_label(metadata, document, field: field_name) %></dt>
          <dd class="blacklight-<%= field_name.parameterize %>"><%= doc_presenter.field_value field %></dd>
        <% end %>
      <% end %>
    <% end %>
  </dl>
<% end %>

app/views/catalog/_sort_and_per_page.html.erb
<% # overidden from Blacklight to handle our responsive needs %>
<div id="sortAndPerPage" class="sort-pagination clearfix">
  <div>
    <%= render partial: "paginate_compact", object: @response if show_pagination? %>
  </div>
  <%= render partial: 'group_toggle'  %>
  <%= render_results_collection_tools wrapping_class: "search-widgets float-md-right" %>
</div>

app/views/catalog/_start_over.html.erb
<%# COPIED FROM BLACKLIGHT v7.11.1 TO REPLACE PATH %>
<%= link_to t('blacklight.search.start_over'), root_path, class: "catalog_startOverLink btn btn-primary" %>